const API_URL = process.env.REACT_APP_API_URL;

const API_ROUTE_AESTHETIC_NAMES = `${API_URL}/aesthetic/names`;
const API_ROUTE_AESTHETIC_FIND_FOR_EDIT = `${API_URL}/aesthetic/findForEdit`;
const API_ROUTE_AESTHETIC_FIND_FOR_LIST = `${API_URL}/aesthetic/findForList`;
const API_ROUTE_AESTHETIC_FIND_FOR_PAGE = `${API_URL}/aesthetic/findForPage`;
const API_ROUTE_AESTHETIC_FIND_GALLERY_CONTENT = `${API_URL}/aesthetic/findGalleryContent`;
const API_ROUTE_AESTHETIC_EDIT = `${API_URL}/aesthetic/edit`;

const API_ROUTE_AUTH_CHECK_SESSION = `${API_URL}/auth/checkSession`;
const API_ROUTE_AUTH_CHECK_TOKEN = `${API_URL}/auth/checkToken`;
const API_ROUTE_AUTH_LOGIN = `${API_URL}/auth/login`;
const API_ROUTE_AUTH_LOGOUT = `${API_URL}/auth/logout`;

const API_ROUTE_MEDIA_CREATORS = `${API_URL}/mediaCreators`;

const API_ROUTE_USER_CONFIRM = `${API_URL}/user/confirm`;
const API_ROUTE_USER_FORGOT_PASSWORD = `${API_URL}/mail/forgotPassword`;
const API_ROUTE_USER_REGISTER = `${API_URL}/user/register`;
const API_ROUTE_USER_RESET_PASSWORD = `${API_URL}/user/resetPassword`;

const API_ROUTE_WEBSITE_TYPES = `${API_URL}/websiteTypes`;

const ARENA_API_URL = 'https://api.are.na/v2/channels/';
const WEBSITE_TYPE_ARENA = 1;

export {
  API_ROUTE_AESTHETIC_NAMES,
  API_ROUTE_AESTHETIC_FIND_FOR_EDIT,
  API_ROUTE_AESTHETIC_FIND_FOR_LIST,
  API_ROUTE_AESTHETIC_FIND_FOR_PAGE,
  API_ROUTE_AESTHETIC_FIND_GALLERY_CONTENT,
  API_ROUTE_AESTHETIC_EDIT,
  API_ROUTE_AUTH_CHECK_SESSION,
  API_ROUTE_AUTH_CHECK_TOKEN,
  API_ROUTE_AUTH_LOGIN,
  API_ROUTE_AUTH_LOGOUT,
  API_ROUTE_MEDIA_CREATORS,
  API_ROUTE_USER_CONFIRM,
  API_ROUTE_USER_FORGOT_PASSWORD,
  API_ROUTE_USER_REGISTER,
  API_ROUTE_USER_RESET_PASSWORD,
  API_ROUTE_WEBSITE_TYPES,
  ARENA_API_URL,
  WEBSITE_TYPE_ARENA,
};